package net.minegate.fr.moreblocks;

import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.client.rendereregistry.v1.EntityRendererRegistry;
import net.fabricmc.fabric.api.client.rendering.v1.ColorProviderRegistry;
import net.minecraft.client.color.world.BiomeColors;
import net.minecraft.client.color.world.FoliageColors;
import net.minecraft.client.color.world.GrassColors;
import net.minecraft.client.render.RenderLayer;
import net.minegate.fr.moreblocks.block.Blocks;
import net.minegate.fr.moreblocks.block.entity.SitEntityRenderer;
import net.minegate.fr.moreblocks.block.entity.SitManager;
import net.minegate.fr.moreblocks.item.Items;

import static net.minegate.fr.moreblocks.MoreBlocks.ConsoleClient;
import static net.minegate.fr.moreblocks.MoreBlocks.DebugClient;

public class MoreBlocksClient implements ClientModInitializer
{
    /**
     * Initialization.
     **/

    @Override
    public void onInitializeClient()
    {
        EntityRendererRegistry.INSTANCE.register(SitManager.SIT_ENTITY_TYPE, SitEntityRenderer::new);
        if (DebugClient())
        {
            ConsoleClient("EntityRendererRegistry : OK !");
        }
        BlockRenderLayerMap.INSTANCE.putBlocks(RenderLayer.getTranslucent(),
                Blocks.GLASS_STAIRS,
                Blocks.GLASS_STAIRS_VERTICAL,
                Blocks.GLASS_SLAB,
                Blocks.GLASS_SLAB_VERTICAL,
                Blocks.GLASS_QUARTER,
                Blocks.GLASS_QUARTER_VERTICAL,
                Blocks.GLASS_EIGHTH,
                Blocks.TINTED_GLASS_STAIRS,
                Blocks.TINTED_GLASS_STAIRS_VERTICAL,
                Blocks.TINTED_GLASS_SLAB,
                Blocks.TINTED_GLASS_SLAB_VERTICAL,
                Blocks.TINTED_GLASS_QUARTER,
                Blocks.TINTED_GLASS_QUARTER_VERTICAL,
                Blocks.TINTED_GLASS_EIGHTH,
                Blocks.ICE_STAIRS,
                Blocks.ICE_STAIRS_VERTICAL,
                Blocks.ICE_SLAB,
                Blocks.ICE_SLAB_VERTICAL,
                Blocks.ICE_QUARTER,
                Blocks.ICE_QUARTER_VERTICAL,
                Blocks.ICE_EIGHTH,
                Blocks.BLACK_STAINED_GLASS_STAIRS,
                Blocks.BLUE_STAINED_GLASS_STAIRS,
                Blocks.BROWN_STAINED_GLASS_STAIRS,
                Blocks.CYAN_STAINED_GLASS_STAIRS,
                Blocks.GRAY_STAINED_GLASS_STAIRS,
                Blocks.GREEN_STAINED_GLASS_STAIRS,
                Blocks.LIGHT_BLUE_STAINED_GLASS_STAIRS,
                Blocks.LIGHT_GRAY_STAINED_GLASS_STAIRS,
                Blocks.LIME_STAINED_GLASS_STAIRS,
                Blocks.MAGENTA_STAINED_GLASS_STAIRS,
                Blocks.ORANGE_STAINED_GLASS_STAIRS,
                Blocks.PINK_STAINED_GLASS_STAIRS,
                Blocks.PURPLE_STAINED_GLASS_STAIRS,
                Blocks.RED_STAINED_GLASS_STAIRS,
                Blocks.WHITE_STAINED_GLASS_STAIRS,
                Blocks.YELLOW_STAINED_GLASS_STAIRS,
                Blocks.BLACK_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.BLUE_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.BROWN_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.CYAN_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.GRAY_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.GREEN_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.LIGHT_BLUE_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.LIGHT_GRAY_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.LIME_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.MAGENTA_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.ORANGE_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.PINK_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.PURPLE_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.RED_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.WHITE_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.YELLOW_STAINED_GLASS_STAIRS_VERTICAL,
                Blocks.BLACK_STAINED_GLASS_SLAB,
                Blocks.BLUE_STAINED_GLASS_SLAB,
                Blocks.BROWN_STAINED_GLASS_SLAB,
                Blocks.CYAN_STAINED_GLASS_SLAB,
                Blocks.GRAY_STAINED_GLASS_SLAB,
                Blocks.GREEN_STAINED_GLASS_SLAB,
                Blocks.LIGHT_BLUE_STAINED_GLASS_SLAB,
                Blocks.LIGHT_GRAY_STAINED_GLASS_SLAB,
                Blocks.LIME_STAINED_GLASS_SLAB,
                Blocks.MAGENTA_STAINED_GLASS_SLAB,
                Blocks.ORANGE_STAINED_GLASS_SLAB,
                Blocks.PINK_STAINED_GLASS_SLAB,
                Blocks.PURPLE_STAINED_GLASS_SLAB,
                Blocks.RED_STAINED_GLASS_SLAB,
                Blocks.WHITE_STAINED_GLASS_SLAB,
                Blocks.YELLOW_STAINED_GLASS_SLAB,
                Blocks.BLACK_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.BLUE_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.BROWN_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.CYAN_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.GRAY_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.GREEN_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.LIGHT_BLUE_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.LIGHT_GRAY_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.LIME_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.MAGENTA_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.ORANGE_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.PINK_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.PURPLE_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.RED_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.WHITE_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.YELLOW_STAINED_GLASS_SLAB_VERTICAL,
                Blocks.BLACK_STAINED_GLASS_QUARTER,
                Blocks.BLUE_STAINED_GLASS_QUARTER,
                Blocks.BROWN_STAINED_GLASS_QUARTER,
                Blocks.CYAN_STAINED_GLASS_QUARTER,
                Blocks.GRAY_STAINED_GLASS_QUARTER,
                Blocks.GREEN_STAINED_GLASS_QUARTER,
                Blocks.LIGHT_BLUE_STAINED_GLASS_QUARTER,
                Blocks.LIGHT_GRAY_STAINED_GLASS_QUARTER,
                Blocks.LIME_STAINED_GLASS_QUARTER,
                Blocks.MAGENTA_STAINED_GLASS_QUARTER,
                Blocks.ORANGE_STAINED_GLASS_QUARTER,
                Blocks.PINK_STAINED_GLASS_QUARTER,
                Blocks.PURPLE_STAINED_GLASS_QUARTER,
                Blocks.RED_STAINED_GLASS_QUARTER,
                Blocks.WHITE_STAINED_GLASS_QUARTER,
                Blocks.YELLOW_STAINED_GLASS_QUARTER,
                Blocks.BLACK_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.BLUE_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.BROWN_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.CYAN_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.GRAY_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.GREEN_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.LIGHT_BLUE_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.LIGHT_GRAY_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.LIME_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.MAGENTA_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.ORANGE_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.PINK_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.PURPLE_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.RED_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.WHITE_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.YELLOW_STAINED_GLASS_QUARTER_VERTICAL,
                Blocks.BLACK_STAINED_GLASS_EIGHTH,
                Blocks.BLUE_STAINED_GLASS_EIGHTH,
                Blocks.BROWN_STAINED_GLASS_EIGHTH,
                Blocks.CYAN_STAINED_GLASS_EIGHTH,
                Blocks.GRAY_STAINED_GLASS_EIGHTH,
                Blocks.GREEN_STAINED_GLASS_EIGHTH,
                Blocks.LIGHT_BLUE_STAINED_GLASS_EIGHTH,
                Blocks.LIGHT_GRAY_STAINED_GLASS_EIGHTH,
                Blocks.LIME_STAINED_GLASS_EIGHTH,
                Blocks.MAGENTA_STAINED_GLASS_EIGHTH,
                Blocks.ORANGE_STAINED_GLASS_EIGHTH,
                Blocks.PINK_STAINED_GLASS_EIGHTH,
                Blocks.PURPLE_STAINED_GLASS_EIGHTH,
                Blocks.RED_STAINED_GLASS_EIGHTH,
                Blocks.WHITE_STAINED_GLASS_EIGHTH,
                Blocks.YELLOW_STAINED_GLASS_EIGHTH,
                Blocks.OAK_LEAVES_STAIRS,
                Blocks.OAK_LEAVES_STAIRS_VERTICAL,
                Blocks.OAK_LEAVES_SLAB,
                Blocks.OAK_LEAVES_SLAB_VERTICAL,
                Blocks.OAK_LEAVES_QUARTER,
                Blocks.OAK_LEAVES_QUARTER_VERTICAL,
                Blocks.OAK_LEAVES_EIGHTH,
                Blocks.SPRUCE_LEAVES_STAIRS,
                Blocks.SPRUCE_LEAVES_STAIRS_VERTICAL,
                Blocks.SPRUCE_LEAVES_SLAB,
                Blocks.SPRUCE_LEAVES_SLAB_VERTICAL,
                Blocks.SPRUCE_LEAVES_QUARTER,
                Blocks.SPRUCE_LEAVES_QUARTER_VERTICAL,
                Blocks.SPRUCE_LEAVES_EIGHTH,
                Blocks.BIRCH_LEAVES_STAIRS,
                Blocks.BIRCH_LEAVES_STAIRS_VERTICAL,
                Blocks.BIRCH_LEAVES_SLAB,
                Blocks.BIRCH_LEAVES_SLAB_VERTICAL,
                Blocks.BIRCH_LEAVES_QUARTER,
                Blocks.BIRCH_LEAVES_QUARTER_VERTICAL,
                Blocks.BIRCH_LEAVES_EIGHTH,
                Blocks.JUNGLE_LEAVES_STAIRS,
                Blocks.JUNGLE_LEAVES_STAIRS_VERTICAL,
                Blocks.JUNGLE_LEAVES_SLAB,
                Blocks.JUNGLE_LEAVES_SLAB_VERTICAL,
                Blocks.JUNGLE_LEAVES_QUARTER,
                Blocks.JUNGLE_LEAVES_QUARTER_VERTICAL,
                Blocks.JUNGLE_LEAVES_EIGHTH,
                Blocks.ACACIA_LEAVES_STAIRS,
                Blocks.ACACIA_LEAVES_STAIRS_VERTICAL,
                Blocks.ACACIA_LEAVES_SLAB,
                Blocks.ACACIA_LEAVES_SLAB_VERTICAL,
                Blocks.ACACIA_LEAVES_QUARTER,
                Blocks.ACACIA_LEAVES_QUARTER_VERTICAL,
                Blocks.ACACIA_LEAVES_EIGHTH,
                Blocks.DARK_OAK_LEAVES_STAIRS,
                Blocks.DARK_OAK_LEAVES_STAIRS_VERTICAL,
                Blocks.DARK_OAK_LEAVES_SLAB,
                Blocks.DARK_OAK_LEAVES_SLAB_VERTICAL,
                Blocks.DARK_OAK_LEAVES_QUARTER,
                Blocks.DARK_OAK_LEAVES_QUARTER_VERTICAL,
                Blocks.DARK_OAK_LEAVES_EIGHTH,
                Blocks.AZALEA_LEAVES_STAIRS,
                Blocks.AZALEA_LEAVES_STAIRS_VERTICAL,
                Blocks.AZALEA_LEAVES_SLAB,
                Blocks.AZALEA_LEAVES_SLAB_VERTICAL,
                Blocks.AZALEA_LEAVES_QUARTER,
                Blocks.AZALEA_LEAVES_QUARTER_VERTICAL,
                Blocks.AZALEA_LEAVES_EIGHTH,
                Blocks.FLOWERING_AZALEA_LEAVES_STAIRS,
                Blocks.FLOWERING_AZALEA_LEAVES_STAIRS_VERTICAL,
                Blocks.FLOWERING_AZALEA_LEAVES_SLAB,
                Blocks.FLOWERING_AZALEA_LEAVES_SLAB_VERTICAL,
                Blocks.FLOWERING_AZALEA_LEAVES_QUARTER,
                Blocks.FLOWERING_AZALEA_LEAVES_QUARTER_VERTICAL,
                Blocks.FLOWERING_AZALEA_LEAVES_EIGHTH,
                Blocks.WOODCUTTER,
                Blocks.SPRUCE_LADDER,
                Blocks.BIRCH_LADDER,
                Blocks.JUNGLE_LADDER,
                Blocks.ACACIA_LADDER,
                Blocks.DARK_OAK_LADDER,
                Blocks.CRIMSON_LADDER,
                Blocks.WARPED_LADDER
        );
        BlockRenderLayerMap.INSTANCE.putBlocks(RenderLayer.getCutoutMipped(),
                Blocks.GRASS_BLOCK_SLAB,
                Blocks.DIRT_SLAB,
                Blocks.COARSE_DIRT_SLAB,
                Blocks.PODZOL_SLAB
        );
        ColorProviderRegistry.BLOCK.register((state, world, pos, tintIndex) -> FoliageColors.getSpruceColor(),
                Blocks.SPRUCE_LEAVES_STAIRS, Blocks.SPRUCE_LEAVES_STAIRS_VERTICAL, Blocks.SPRUCE_LEAVES_SLAB, Blocks.SPRUCE_LEAVES_SLAB_VERTICAL, Blocks.SPRUCE_LEAVES_QUARTER, Blocks.SPRUCE_LEAVES_QUARTER_VERTICAL, Blocks.SPRUCE_LEAVES_EIGHTH
        );
        ColorProviderRegistry.BLOCK.register((state, world, pos, tintIndex) -> FoliageColors.getBirchColor(),
                Blocks.BIRCH_LEAVES_STAIRS, Blocks.BIRCH_LEAVES_STAIRS_VERTICAL, Blocks.BIRCH_LEAVES_SLAB, Blocks.BIRCH_LEAVES_SLAB_VERTICAL, Blocks.BIRCH_LEAVES_QUARTER, Blocks.BIRCH_LEAVES_QUARTER_VERTICAL, Blocks.BIRCH_LEAVES_EIGHTH
        );
        ColorProviderRegistry.BLOCK.register((state, world, pos, tintIndex) -> world != null && pos != null ? BiomeColors.getFoliageColor(world, pos) : FoliageColors.getDefaultColor(),
                Blocks.OAK_LEAVES_STAIRS, Blocks.OAK_LEAVES_STAIRS_VERTICAL, Blocks.OAK_LEAVES_SLAB, Blocks.OAK_LEAVES_SLAB_VERTICAL, Blocks.OAK_LEAVES_QUARTER, Blocks.OAK_LEAVES_QUARTER_VERTICAL, Blocks.OAK_LEAVES_EIGHTH,
                Blocks.JUNGLE_LEAVES_STAIRS, Blocks.JUNGLE_LEAVES_STAIRS_VERTICAL, Blocks.JUNGLE_LEAVES_SLAB, Blocks.JUNGLE_LEAVES_SLAB_VERTICAL, Blocks.JUNGLE_LEAVES_QUARTER, Blocks.JUNGLE_LEAVES_QUARTER_VERTICAL, Blocks.JUNGLE_LEAVES_EIGHTH,
                Blocks.ACACIA_LEAVES_STAIRS, Blocks.ACACIA_LEAVES_STAIRS_VERTICAL, Blocks.ACACIA_LEAVES_SLAB, Blocks.ACACIA_LEAVES_SLAB_VERTICAL, Blocks.ACACIA_LEAVES_QUARTER, Blocks.ACACIA_LEAVES_QUARTER_VERTICAL, Blocks.ACACIA_LEAVES_EIGHTH,
                Blocks.DARK_OAK_LEAVES_STAIRS, Blocks.DARK_OAK_LEAVES_STAIRS_VERTICAL, Blocks.DARK_OAK_LEAVES_SLAB, Blocks.DARK_OAK_LEAVES_SLAB_VERTICAL, Blocks.DARK_OAK_LEAVES_QUARTER, Blocks.DARK_OAK_LEAVES_QUARTER_VERTICAL, Blocks.DARK_OAK_LEAVES_EIGHTH
        );
        ColorProviderRegistry.BLOCK.register((state, view, pos, tintIndex) ->
        {
            if (tintIndex == 1)
                return view != null && pos != null ? BiomeColors.getGrassColor(view, pos) : GrassColors.getColor(0.5D, 1.0D);

            return -1;
        }, Blocks.GRASS_BLOCK_SLAB, Blocks.DIRT_SLAB, Blocks.COARSE_DIRT_SLAB, Blocks.PODZOL_SLAB);
        BlockRenderLayerMap.INSTANCE.putItems(RenderLayer.getTranslucent(),
                Items.BLACK_STAINED_GLASS_STAIRS,
                Items.BLUE_STAINED_GLASS_STAIRS,
                Items.BROWN_STAINED_GLASS_STAIRS,
                Items.CYAN_STAINED_GLASS_STAIRS,
                Items.GRAY_STAINED_GLASS_STAIRS,
                Items.GREEN_STAINED_GLASS_STAIRS,
                Items.LIGHT_BLUE_STAINED_GLASS_STAIRS,
                Items.LIGHT_GRAY_STAINED_GLASS_STAIRS,
                Items.LIME_STAINED_GLASS_STAIRS,
                Items.MAGENTA_STAINED_GLASS_STAIRS,
                Items.ORANGE_STAINED_GLASS_STAIRS,
                Items.PINK_STAINED_GLASS_STAIRS,
                Items.PURPLE_STAINED_GLASS_STAIRS,
                Items.RED_STAINED_GLASS_STAIRS,
                Items.WHITE_STAINED_GLASS_STAIRS,
                Items.YELLOW_STAINED_GLASS_STAIRS,
                Items.BLACK_STAINED_GLASS_STAIRS_VERTICAL,
                Items.BLUE_STAINED_GLASS_STAIRS_VERTICAL,
                Items.BROWN_STAINED_GLASS_STAIRS_VERTICAL,
                Items.CYAN_STAINED_GLASS_STAIRS_VERTICAL,
                Items.GRAY_STAINED_GLASS_STAIRS_VERTICAL,
                Items.GREEN_STAINED_GLASS_STAIRS_VERTICAL,
                Items.LIGHT_BLUE_STAINED_GLASS_STAIRS_VERTICAL,
                Items.LIGHT_GRAY_STAINED_GLASS_STAIRS_VERTICAL,
                Items.LIME_STAINED_GLASS_STAIRS_VERTICAL,
                Items.MAGENTA_STAINED_GLASS_STAIRS_VERTICAL,
                Items.ORANGE_STAINED_GLASS_STAIRS_VERTICAL,
                Items.PINK_STAINED_GLASS_STAIRS_VERTICAL,
                Items.PURPLE_STAINED_GLASS_STAIRS_VERTICAL,
                Items.RED_STAINED_GLASS_STAIRS_VERTICAL,
                Items.WHITE_STAINED_GLASS_STAIRS_VERTICAL,
                Items.YELLOW_STAINED_GLASS_STAIRS_VERTICAL,
                Items.BLACK_STAINED_GLASS_SLAB,
                Items.BLUE_STAINED_GLASS_SLAB,
                Items.BROWN_STAINED_GLASS_SLAB,
                Items.CYAN_STAINED_GLASS_SLAB,
                Items.GRAY_STAINED_GLASS_SLAB,
                Items.GREEN_STAINED_GLASS_SLAB,
                Items.LIGHT_BLUE_STAINED_GLASS_SLAB,
                Items.LIGHT_GRAY_STAINED_GLASS_SLAB,
                Items.LIME_STAINED_GLASS_SLAB,
                Items.MAGENTA_STAINED_GLASS_SLAB,
                Items.ORANGE_STAINED_GLASS_SLAB,
                Items.PINK_STAINED_GLASS_SLAB,
                Items.PURPLE_STAINED_GLASS_SLAB,
                Items.RED_STAINED_GLASS_SLAB,
                Items.WHITE_STAINED_GLASS_SLAB,
                Items.YELLOW_STAINED_GLASS_SLAB,
                Items.BLACK_STAINED_GLASS_SLAB_VERTICAL,
                Items.BLUE_STAINED_GLASS_SLAB_VERTICAL,
                Items.BROWN_STAINED_GLASS_SLAB_VERTICAL,
                Items.CYAN_STAINED_GLASS_SLAB_VERTICAL,
                Items.GRAY_STAINED_GLASS_SLAB_VERTICAL,
                Items.GREEN_STAINED_GLASS_SLAB_VERTICAL,
                Items.LIGHT_BLUE_STAINED_GLASS_SLAB_VERTICAL,
                Items.LIGHT_GRAY_STAINED_GLASS_SLAB_VERTICAL,
                Items.LIME_STAINED_GLASS_SLAB_VERTICAL,
                Items.MAGENTA_STAINED_GLASS_SLAB_VERTICAL,
                Items.ORANGE_STAINED_GLASS_SLAB_VERTICAL,
                Items.PINK_STAINED_GLASS_SLAB_VERTICAL,
                Items.PURPLE_STAINED_GLASS_SLAB_VERTICAL,
                Items.RED_STAINED_GLASS_SLAB_VERTICAL,
                Items.WHITE_STAINED_GLASS_SLAB_VERTICAL,
                Items.YELLOW_STAINED_GLASS_SLAB_VERTICAL,
                Items.BLACK_STAINED_GLASS_QUARTER,
                Items.BLUE_STAINED_GLASS_QUARTER,
                Items.BROWN_STAINED_GLASS_QUARTER,
                Items.CYAN_STAINED_GLASS_QUARTER,
                Items.GRAY_STAINED_GLASS_QUARTER,
                Items.GREEN_STAINED_GLASS_QUARTER,
                Items.LIGHT_BLUE_STAINED_GLASS_QUARTER,
                Items.LIGHT_GRAY_STAINED_GLASS_QUARTER,
                Items.LIME_STAINED_GLASS_QUARTER,
                Items.MAGENTA_STAINED_GLASS_QUARTER,
                Items.ORANGE_STAINED_GLASS_QUARTER,
                Items.PINK_STAINED_GLASS_QUARTER,
                Items.PURPLE_STAINED_GLASS_QUARTER,
                Items.RED_STAINED_GLASS_QUARTER,
                Items.WHITE_STAINED_GLASS_QUARTER,
                Items.YELLOW_STAINED_GLASS_QUARTER,
                Items.BLACK_STAINED_GLASS_QUARTER_VERTICAL,
                Items.BLUE_STAINED_GLASS_QUARTER_VERTICAL,
                Items.BROWN_STAINED_GLASS_QUARTER_VERTICAL,
                Items.CYAN_STAINED_GLASS_QUARTER_VERTICAL,
                Items.GRAY_STAINED_GLASS_QUARTER_VERTICAL,
                Items.GREEN_STAINED_GLASS_QUARTER_VERTICAL,
                Items.LIGHT_BLUE_STAINED_GLASS_QUARTER_VERTICAL,
                Items.LIGHT_GRAY_STAINED_GLASS_QUARTER_VERTICAL,
                Items.LIME_STAINED_GLASS_QUARTER_VERTICAL,
                Items.MAGENTA_STAINED_GLASS_QUARTER_VERTICAL,
                Items.ORANGE_STAINED_GLASS_QUARTER_VERTICAL,
                Items.PINK_STAINED_GLASS_QUARTER_VERTICAL,
                Items.PURPLE_STAINED_GLASS_QUARTER_VERTICAL,
                Items.RED_STAINED_GLASS_QUARTER_VERTICAL,
                Items.WHITE_STAINED_GLASS_QUARTER_VERTICAL,
                Items.YELLOW_STAINED_GLASS_QUARTER_VERTICAL,
                Items.BLACK_STAINED_GLASS_EIGHTH,
                Items.BLUE_STAINED_GLASS_EIGHTH,
                Items.BROWN_STAINED_GLASS_EIGHTH,
                Items.CYAN_STAINED_GLASS_EIGHTH,
                Items.GRAY_STAINED_GLASS_EIGHTH,
                Items.GREEN_STAINED_GLASS_EIGHTH,
                Items.LIGHT_BLUE_STAINED_GLASS_EIGHTH,
                Items.LIGHT_GRAY_STAINED_GLASS_EIGHTH,
                Items.LIME_STAINED_GLASS_EIGHTH,
                Items.MAGENTA_STAINED_GLASS_EIGHTH,
                Items.ORANGE_STAINED_GLASS_EIGHTH,
                Items.PINK_STAINED_GLASS_EIGHTH,
                Items.PURPLE_STAINED_GLASS_EIGHTH,
                Items.RED_STAINED_GLASS_EIGHTH,
                Items.WHITE_STAINED_GLASS_EIGHTH,
                Items.YELLOW_STAINED_GLASS_EIGHTH
        );
        ColorProviderRegistry.ITEM.register((stack, tintIndex) -> FoliageColors.getSpruceColor(),
                Blocks.SPRUCE_LEAVES_STAIRS, Blocks.SPRUCE_LEAVES_STAIRS_VERTICAL, Blocks.SPRUCE_LEAVES_SLAB, Blocks.SPRUCE_LEAVES_SLAB_VERTICAL, Blocks.SPRUCE_LEAVES_QUARTER, Blocks.SPRUCE_LEAVES_QUARTER_VERTICAL, Blocks.SPRUCE_LEAVES_EIGHTH
        );
        ColorProviderRegistry.ITEM.register((stack, tintIndex) -> FoliageColors.getBirchColor(),
                Blocks.BIRCH_LEAVES_STAIRS, Blocks.BIRCH_LEAVES_STAIRS_VERTICAL, Blocks.BIRCH_LEAVES_SLAB, Blocks.BIRCH_LEAVES_SLAB_VERTICAL, Blocks.BIRCH_LEAVES_QUARTER, Blocks.BIRCH_LEAVES_QUARTER_VERTICAL, Blocks.BIRCH_LEAVES_EIGHTH
        );
        ColorProviderRegistry.ITEM.register((stack, tintIndex) -> FoliageColors.getDefaultColor(),
                Blocks.OAK_LEAVES_STAIRS, Blocks.OAK_LEAVES_STAIRS_VERTICAL, Blocks.OAK_LEAVES_SLAB, Blocks.OAK_LEAVES_SLAB_VERTICAL, Blocks.OAK_LEAVES_QUARTER, Blocks.OAK_LEAVES_QUARTER_VERTICAL, Blocks.OAK_LEAVES_EIGHTH,
                Blocks.JUNGLE_LEAVES_STAIRS, Blocks.JUNGLE_LEAVES_STAIRS_VERTICAL, Blocks.JUNGLE_LEAVES_SLAB, Blocks.JUNGLE_LEAVES_SLAB_VERTICAL, Blocks.JUNGLE_LEAVES_QUARTER, Blocks.JUNGLE_LEAVES_QUARTER_VERTICAL, Blocks.JUNGLE_LEAVES_EIGHTH,
                Blocks.ACACIA_LEAVES_STAIRS, Blocks.ACACIA_LEAVES_STAIRS_VERTICAL, Blocks.ACACIA_LEAVES_SLAB, Blocks.ACACIA_LEAVES_SLAB_VERTICAL, Blocks.ACACIA_LEAVES_QUARTER, Blocks.ACACIA_LEAVES_QUARTER_VERTICAL, Blocks.ACACIA_LEAVES_EIGHTH,
                Blocks.DARK_OAK_LEAVES_STAIRS, Blocks.DARK_OAK_LEAVES_STAIRS_VERTICAL, Blocks.DARK_OAK_LEAVES_SLAB, Blocks.DARK_OAK_LEAVES_SLAB_VERTICAL, Blocks.DARK_OAK_LEAVES_QUARTER, Blocks.DARK_OAK_LEAVES_QUARTER_VERTICAL, Blocks.DARK_OAK_LEAVES_EIGHTH
        );
        ColorProviderRegistry.ITEM.register((stack, tintIndex) -> GrassColors.getColor(0.5D, 1.0D), Blocks.GRASS_BLOCK_SLAB, Blocks.DIRT_SLAB, Blocks.COARSE_DIRT_SLAB, Blocks.PODZOL_SLAB);
        if (DebugClient())
        {
            ConsoleClient("BlockRenderLayerMap & ColorProviderRegistry : OK !");
        }
        ConsoleClient("All is well! Good game with MineGate!");
    }
}